"""initialize models

Revision ID: 59df0866b02a
Revises: 
Create Date: 2020-03-15 20:43:06.005586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59df0866b02a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corona__person',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('town', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.Unicode(length=20), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('type_of_person', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_corona__person_created_at'), 'corona__person', ['created_at'], unique=False)
    op.create_index(op.f('ix_corona__person_gender'), 'corona__person', ['gender'], unique=False)
    op.create_index(op.f('ix_corona__person_id'), 'corona__person', ['id'], unique=False)
    op.create_index(op.f('ix_corona__person_name'), 'corona__person', ['name'], unique=False)
    op.create_index(op.f('ix_corona__person_type_of_person'), 'corona__person', ['type_of_person'], unique=False)
    op.create_index(op.f('ix_corona__person_updated_at'), 'corona__person', ['updated_at'], unique=False)
    op.create_table('corona__association',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('suspect_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('category_of_suspect', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['corona__person.id'], ),
    sa.ForeignKeyConstraint(['suspect_id'], ['corona__person.id'], ),
    sa.PrimaryKeyConstraint('id', 'patient_id', 'suspect_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_corona__association_created_at'), 'corona__association', ['created_at'], unique=False)
    op.create_index(op.f('ix_corona__association_id'), 'corona__association', ['id'], unique=False)
    op.create_index(op.f('ix_corona__association_updated_at'), 'corona__association', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corona__association_updated_at'), table_name='corona__association')
    op.drop_index(op.f('ix_corona__association_id'), table_name='corona__association')
    op.drop_index(op.f('ix_corona__association_created_at'), table_name='corona__association')
    op.drop_table('corona__association')
    op.drop_index(op.f('ix_corona__person_updated_at'), table_name='corona__person')
    op.drop_index(op.f('ix_corona__person_type_of_person'), table_name='corona__person')
    op.drop_index(op.f('ix_corona__person_name'), table_name='corona__person')
    op.drop_index(op.f('ix_corona__person_id'), table_name='corona__person')
    op.drop_index(op.f('ix_corona__person_gender'), table_name='corona__person')
    op.drop_index(op.f('ix_corona__person_created_at'), table_name='corona__person')
    op.drop_table('corona__person')
    # ### end Alembic commands ###
